name: Build Website

on:
  workflow_dispatch:
      inputs:
        s3_admin_url:
          description: 'URL to your S3 Admin API'
          required: true

jobs:
  buildzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop -c pnpm i
      - run: echo "VITE_GARAGE_ADMIN_API_URL=${{ github.event.inputs.s3_admin_url }}" > .env
      - run: nix develop -c node ./scripts/mk-release.js 
      - uses: actions/upload-artifact@v3.2.1-node20
        with:
          path: release-*.zip

# jobs:
#   enter-dev-shell:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Install Nix
#         run: curl -L https://nixos.org/nix/install | sh

#       - name: Enter devShell
#         run: |
#           mkdir -p ~/.config/nix
#           echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
#       - name: Install pnpm packages
#         run: |
#           nix develop
#           pnpm i
#       - name: Build Application
#         run: |
#           nix develop
#           echo "VITE_GARAGE_ADMIN_API_URL=${{ github.event.inputs.s3_admin_url }}" > .env
#           node ./scripts/mk-release.js
#       - name: Upload a Build Artifact
#         uses: actions/upload-artifact@v3.2.1-node20
#         with:
#           path: release-*.zip
        
        


# name: "Test"
# on:
#   pull_request:
#   push:
# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: cachix/install-nix-action@v27
#       with:
#         nix_path: nixpkgs=channel:nixos-unstable
#     - run: nix-build