name: Build Website

on:
  workflow_dispatch:
      inputs:
        s3_admin_url:
          description: 'URL to your S3 Admin API'
          required: true

jobs:
  buildzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop -c pnpm i
      - run: echo "VITE_GARAGE_ADMIN_API_URL=${{ github.event.inputs.s3_admin_url }}" > .env
      - run: nix develop -c node ./scripts/mk-release.js 
      - uses: actions/upload-artifact@v3.2.1-node20
        with:
          path: release-*.zip

